@startuml
'https://plantuml.com/activity-diagram-beta

start
:Lexical Analysis;
:Tokenization;
:Parsing;
partition Semantic Analysis {
    :Begin Semantic Analysis;
    if (undefined element found) then (false)
    else (true)
    partition Import Resolution {
    repeat
        :Locate Import;
        :Lexical Analysis on Import;
        :Tokenization on Import;
        :Parsing on Import;
        :Check export for the undefined element;
        if (export contains undefined element) then (true)
            :Module Level Analysis to get Type;
        else (false)
        endif
        repeat while (undefined element not resolved **AND** Imports remaining)
        ' we have to consider all imports because of overloading and elements with the same name in general
    }
    endif
    :Continue Semantic Analysis;
}
:Code Generation;
stop

@enduml