package de.nikschadowsky.baall.compiler.syntaxtree.ast;

/**
 * @since 29.07.2024
 */
public enum NodeType {
    PROGRAM,
    IMPORT,
    STATEMENTS,
    EXPORT,
    WHILE,
    FOR,
    CONSTANT_DECLARATION,
    VARIABLE_DECLARATION,

    VARIABLE_REASSIGNMENT,
    FUNCTION_CALL,
    FUNCTION_DEFINITION,
    CONTROL_STRUCTURE,
    IDENTIFIER,
    TYPE,
    ANONYMOUS,
    PRIMITIVE,
    STRUCT_DEFINITION,
    STRUCT_INITIALIZATION,
    ARRAY_LITERAL,
    UNARY_EXPRESSION,
    IF,
    PAREN_EXPRESSION,
    BINARY_EXPRESSION,
    PREFIX_OPERATION,
    IDENTIFIER_ACCESS,

    CONTINUE, BREAK, RETURN, RAISE,

    EXCEPTION_CREATION,
    TRY, INTERCEPT, ENSURE
}
