package de.nikschadowsky.baall.compiler.syntax.tree.ast;

/**
 * @since 29.07.2024
 */
public enum NodeType {
    PROGRAM,
    IMPORT,
    STATEMENTS,
    EXPORT,
    WHILE,
    FOR,
    CONSTANT_DECLARATION,
    VARIABLE_DECLARATION,

    VARIABLE_REASSIGNMENT,
    FUNCTION_CALL,
    FUNCTION_DEFINITION,
    CONTROL_STRUCTURE,
    IDENTIFIER,
    ANONYMOUS,
    PRIMITIVE,
    STRUCT_DEFINITION,
    STRUCT_INITIALIZATION,
    ARRAY_LITERAL,
    UNARY_EXPRESSION,
    IF,
    PAREN_EXPRESSION,
    BINARY_EXPRESSION,
    PREFIX_OPERATION,
    IDENTIFIER_ACCESS,

    CONTINUE, BREAK, RETURN, RAISE,

    EXCEPTION_CREATION,
    TRY, INTERCEPT, ENSURE,

    FIELD,
    OPERATOR,
    NONE,
    PRIMITIVE_TYPE,
    NESTED_TYPE,
    FUNCTION_TYPE,
    IDENTIFIER_TYPE,

    INDEXED_ACCESS,
    SCOPE_ELEVATION,
    MEMBER_REFERENCE,

    NUMBER_LITERAL,
    STRING_LITERAL,
    BOOLEAN_LITERAL,
}
